"""add new columns

Revision ID: a57b350666f6
Revises: 
Create Date: 2025-11-26 17:34:59.712222

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a57b350666f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observacoes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('data_previsao', sa.DateTime(), nullable=True))

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('endereco', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('data_cadastro', sa.DateTime(), nullable=False))
        batch_op.drop_column('criado_em')

    with op.batch_alter_table('veiculos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cor', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veiculos', schema=None) as batch_op:
        batch_op.drop_column('cor')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criado_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column('data_cadastro')
        batch_op.drop_column('endereco')
        batch_op.drop_column('telefone')

    with op.batch_alter_table('servicos', schema=None) as batch_op:
        batch_op.drop_column('data_previsao')
        batch_op.drop_column('observacoes')

    # ### end Alembic commands ###
